site_name: TG - Getúlio Vinicius
site_description: Documentação do Projeto de Software ...
site_author: Getúlio Vinicius <getuliovinits@gmail.com>
google_analytics: ['UA-70830801-13', 'auto']
repo_url: https://github.com/getuliovinicius/trabalho.graduacao
repo_name: GitHub
edit_uri: blob/master/docs/mds/
remote_branch: gh-pages
remote_name: origin
docs_dir: 'mds'
pages:
    - Inicio: index.md
    - Tema 1:
        - Introdução: 'tema-1/00-introducao.md'
    - Tema 2:
        - Introdução: 'tema-2/00-introducao.md'
    - Tema 3:
        - Introdução: 'tema-3/00-introducao.md'
theme: readthedocs
extra:
    version: 1.0
markdown_extensions:
    - smarty
    - nl2br
    - admonition
    - codehilite
    - sane_lists
    - toc:
        permalink: True
        separator: "_"
